### PR TITLE
a few bug fixes

### LINKED ISSUE #1: make migrate command fails
The `make migrate` command failed with below traceback on Pyhton3.7 environment.

```
python3 manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/contrib/admin/__init__.py", line 4, in <module>
    from django.contrib.admin.filters import (
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/contrib/admin/filters.py", line 10, in <module>
    from django.contrib.admin.options import IncorrectLookupParameters
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 13, in <module>
    from django.contrib.admin import helpers, widgets
  File "/home/akgaikwad/projects/makegoalsdaily/venv/lib64/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized
make: *** [Makefile:31: migrate] Error 1

```

### PR DESCRIPTION
**Pull request by sdp5**
closes #1 #2 #3

### CODE REVIEW

**Comment by sdp5** [comment]
@akshay196 please have a look ..

**Comment by akshaygin** [comment]
@sundeep-co-in 

`make initlogin` command shows below output:
```
$ make initlogin 
python3 manage.py initlogin
SuperUser account can only be created if no Accounts exist.
```

**Comment by akshaygin** [comment]
> @sundeep-co-in
> 
> `make initlogin` command shows below output:
> 
> ```
> $ make initlogin 
> python3 manage.py initlogin
> SuperUser account can only be created if no Accounts exist.
> ```

My bad. It is working fine.

code looks good to me

**Comment by sdp5** [comment]
thanks!

**Pull request merged**
