### PR TITLE
added tasks features for goals

### PR DESCRIPTION
**Pull request by sdp5**
Users can now create tasks for goal(s) and chase them.

### CODE REVIEW

**Comment by sdp5** [comment]
@akshay196 Please have a look ..

**Comment by akshaygin** [comment]
@sundeep-co-in Initially I able to add goal. But second time when I am adding goal, the `NoReverseMatch at /dashboard/goals` error occurred. Please refer this traceback http://dpaste.com/3JYPTD6

**Comment by akshaygin** [comment]
@sundeep-co-in 

When selecting `Task Target Date`, the date should not be beyond the `Expected Completion date` of respective goal. correct?

**Comment by akshaygin** [comment]
@sundeep-co-in 

Should we name this column as `Target date` or `Deadline`? It confuses user that it seems like task addition date.

task

**Comment by akshaygin** [comment]
@sundeep-co-in 

Once a goal is achieved, user should not be able to add task to that goal, right?

**Comment by sdp5** [comment]
thanks @akshay196 for the review. responses:

1. `traceback` while adding goals - fixed
2. Please submit an issue for date(s) dependencies.
3. fixed, changed to `deadline`
4. fixed, `tasks` could not be added for completed `goals`.

**Comment by akshaygin** [comment]
@sundeep-co-in It works very well now. :)

**Comment by akshaygin** [comment]
@sundeep-co-in  Should we align/map activity that is to be logged with task instead of goal? What do you think?

**Comment by sdp5** [comment]
Predefined time-bound activities are tasks. _We need to work on rules to include tasks in our reports._

**Review by akshaygin — APPROVED** [review]

**Comment by sdp5** [comment]
thanks @akshay196 merging ..

**Pull request merged**
